# Generated by Django 5.1.15 on 2026-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billableservice",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="insurancescheme",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="patientinsurance",
            options={"ordering": ["-created_at"]},
        ),
    ]
