# Generated by Django 5.1.15 on 2026-06-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("CLINIC", "Clinic"),
                            ("HOSPITAL", "Hospital"),
                            ("LABORATORY", "Diagnostic / Laboratory"),
                            ("PHARMACY", "Pharmacy"),
                            ("GROUP", "Facility group"),
                        ],
                        default="CLINIC",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "tax_identifier",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The organization selected by default at login.",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, help_text="Organization-level administrator."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="tenancy_mem_user_id_b1a960_idx",
                    )
                ],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
