# Generated by Django 5.1.15 on 2026-06-20 23:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DRUG", "Drug"),
                            ("FOOD", "Food"),
                            ("ENVIRONMENT", "Environment"),
                            ("OTHER", "Other"),
                        ],
                        default="DRUG",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reaction", models.CharField(blank=True, default="", max_length=255)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CareSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "care_setting_type",
                    models.CharField(
                        choices=[
                            ("OUTPATIENT", "Outpatient"),
                            ("INPATIENT", "Inpatient"),
                        ],
                        default="OUTPATIENT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "is_set",
                    models.BooleanField(
                        default=False,
                        help_text="True if this concept groups other concepts (a panel/set).",
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=50)),
                ("units", models.CharField(blank=True, default="", max_length=50)),
                ("hi_normal", models.FloatField(blank=True, null=True)),
                ("low_normal", models.FloatField(blank=True, null=True)),
                ("hi_critical", models.FloatField(blank=True, null=True)),
                ("low_critical", models.FloatField(blank=True, null=True)),
                ("hi_absolute", models.FloatField(blank=True, null=True)),
                ("low_absolute", models.FloatField(blank=True, null=True)),
                ("allow_decimal", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_weight", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["sort_weight"],
            },
        ),
        migrations.CreateModel(
            name="ConceptClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name_plural": "concept classes",
            },
        ),
        migrations.CreateModel(
            name="ConceptDatatype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "hl7_abbreviation",
                    models.CharField(blank=True, default="", max_length=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConceptMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("SAME-AS", "Same as"),
                            ("NARROWER-THAN", "Narrower than"),
                            ("BROADER-THAN", "Broader than"),
                            ("RELATED-TO", "Related to"),
                        ],
                        default="SAME-AS",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "locale",
                    models.CharField(db_index=True, default="en", max_length=20),
                ),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("FULLY_SPECIFIED", "Fully specified"),
                            ("SHORT", "Short"),
                            ("SYNONYM", "Synonym"),
                        ],
                        default="SYNONYM",
                        max_length=20,
                    ),
                ),
                ("locale_preferred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptReferenceTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptSetMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_weight", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["sort_weight"],
            },
        ),
        migrations.CreateModel(
            name="ConceptSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("hl7_code", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("PROVISIONAL", "Provisional"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1 = primary diagnosis, 2+ = secondary."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("encounter_datetime", models.DateTimeField(db_index=True)),
                (
                    "form_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional originating form id.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["-encounter_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EncounterProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncounterRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EncounterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("address1", models.CharField(blank=True, default="", max_length=255)),
                (
                    "city_village",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "state_province",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("country", models.CharField(blank=True, default="", max_length=120)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Obs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("obs_datetime", models.DateTimeField(db_index=True)),
                ("value_numeric", models.FloatField(blank=True, null=True)),
                ("value_text", models.TextField(blank=True, default="")),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "value_complex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pointer to complex data (image, file).",
                        max_length=255,
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "Normal"),
                            ("H", "High"),
                            ("L", "Low"),
                            ("HH", "Critical high"),
                            ("LL", "Critical low"),
                            ("A", "Abnormal"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("comments", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        default="FINAL",
                        help_text="PRELIMINARY / FINAL / AMENDED (FHIR observation status).",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-obs_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "order_action",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("REVISE", "Revise"),
                            ("DISCONTINUE", "Discontinue"),
                            ("RENEW", "Renew"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("STAT", "Stat"),
                            ("ON_SCHEDULED_DATE", "On scheduled date"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True, default="")),
                ("date_activated", models.DateTimeField(db_index=True)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("date_stopped", models.DateTimeField(blank=True, null=True)),
                ("auto_expire_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fulfiller_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECEIVED", "Received"),
                            ("IN_PROGRESS", "In progress"),
                            ("EXCEPTION", "Exception"),
                            ("ON_HOLD", "On hold"),
                            ("DECLINED", "Declined"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "fulfiller_comment",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-date_activated"],
            },
        ),
        migrations.CreateModel(
            name="OrderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "java_class_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Backing model, for routing.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "allergy_status",
                    models.CharField(
                        default="Unknown",
                        help_text="Unknown / No Known Allergies / See List",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("identifier", models.CharField(db_index=True, max_length=120)),
                ("preferred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PatientIdentifierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "format_regex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional validation regex.",
                        max_length=255,
                    ),
                ),
                (
                    "format_description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "check_digit_algorithm",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "uniqueness_behavior",
                    models.CharField(
                        choices=[
                            ("UNIQUE", "Unique"),
                            ("NON_UNIQUE", "Non-unique"),
                            ("LOCATION", "Unique per location"),
                        ],
                        default="UNIQUE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_enrolled", models.DateField(db_index=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatientState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("birthdate_estimated", models.BooleanField(default=False)),
                ("dead", models.BooleanField(default=False)),
                ("death_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("preferred", models.BooleanField(default=False)),
                ("address1", models.CharField(blank=True, default="", max_length=255)),
                ("address2", models.CharField(blank=True, default="", max_length=255)),
                (
                    "city_village",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "county_district",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "state_province",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("country", models.CharField(blank=True, default="", max_length=120)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("value", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PersonAttributeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "format",
                    models.CharField(
                        default="java.lang.String",
                        help_text="Logical datatype hint: string, boolean, date, concept, ...",
                        max_length=50,
                    ),
                ),
                ("searchable", models.BooleanField(default=False)),
                ("sort_weight", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["sort_weight", "name"],
            },
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("preferred", models.BooleanField(default=False)),
                ("prefix", models.CharField(blank=True, default="", max_length=50)),
                ("given_name", models.CharField(db_index=True, max_length=120)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("family_name", models.CharField(db_index=True, max_length=120)),
                (
                    "family_name_suffix",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramWorkflowState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("initial", models.BooleanField(default=False)),
                ("terminal", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                (
                    "stopped_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
