# Generated by Django 5.1.15 on 2026-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergy",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="caresetting",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="concept",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="conceptdatatype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="conceptsource",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="condition",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="encounterrole",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="encountertype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="locationtag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ordertype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="patientidentifiertype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="patientstate",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="personaddress",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="programworkflow",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="programworkflowstate",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="visittype",
            options={"ordering": ["name"]},
        ),
    ]
