# Generated by Django 5.1.15 on 2026-06-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("inventory", "0006_purchasebill_purchasebillitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpaymentallocation",
            name="purchase_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="inventory.purchasebill",
            ),
        ),
        migrations.AddField(
            model_name="taxcomponent",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="inventory.taxrate",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["account", "-occurred_at"],
                name="finance_acc_account_09bfc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="finance_acc_referen_aff590_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partyledgerentry",
            index=models.Index(
                fields=["party_content_type", "party_object_id", "entry_date"],
                name="finance_par_party_c_6f9069_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partyledgerentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="finance_par_referen_88602a_idx",
            ),
        ),
    ]
