# Generated by Django 5.1.15 on 2026-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("void", "Void"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("access", "Access"),
                            ("export", "Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=120)),
                (
                    "object_pk",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("object_uuid", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("changes", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlobalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property", models.CharField(max_length=255, unique=True)),
                ("property_value", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "datatype",
                    models.CharField(
                        default="string",
                        help_text="Logical type hint: string, int, boolean, json, ...",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "global property",
                "verbose_name_plural": "global properties",
                "ordering": ["property"],
            },
        ),
    ]
