# Generated by Django 5.1.15 on 2026-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lis", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyzer",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="labsection",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="labtest",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="specimentype",
            options={"ordering": ["name"]},
        ),
    ]
