# Generated by Django 5.1.15 on 2026-06-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lis", "0004_specimen_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("protocol", models.CharField(default="HL7", max_length=20)),
                ("raw_payload", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("PARTIAL", "Partially processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("results_matched", models.PositiveIntegerField(default=0)),
                ("results_unmatched", models.PositiveIntegerField(default=0)),
                ("log", models.JSONField(blank=True, default=list)),
                (
                    "analyzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="lis.analyzer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
