# Generated by Django 5.1.15 on 2026-06-21 05:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0005_cohort_conceptattributetype_conceptattribute_and_more"),
        ("lis", "0005_analyzermessage"),
        ("notifications", "0001_initial"),
        ("users", "0002_providerattributetype_providerattribute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testorder",
            name="is_outsourced",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Antibiotic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutoVerificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "require_in_range",
                    models.BooleanField(
                        default=True,
                        help_text="Only auto-verify results within the reference range.",
                    ),
                ),
                (
                    "block_on_critical",
                    models.BooleanField(
                        default=True,
                        help_text="Never auto-verify a critical/panic result.",
                    ),
                ),
                (
                    "delta_check_percent",
                    models.FloatField(
                        blank=True,
                        help_text="Hold if the result differs from the patient's previous value by more than this %.",
                        null=True,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_verification_rules",
                        to="lis.labtest",
                    ),
                ),
                (
                    "reflex_on_abnormal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Test to auto-order when this result is abnormal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reflex_triggers",
                        to="lis.labtest",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["lab_test"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("CORPORATE", "Corporate"),
                            ("COLLECTION_CENTER", "Collection center"),
                            ("CAMP", "Health camp"),
                            ("OTHER", "Other"),
                        ],
                        default="HOSPITAL",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "is_credit",
                    models.BooleanField(
                        default=False, help_text="Billed on account vs prepaid."
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testorder",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_orders",
                to="lis.client",
            ),
        ),
        migrations.CreateModel(
            name="CollectionCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("is_home_collection", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_centers",
                        to="emr.location",
                    ),
                ),
                (
                    "processing_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_collection_centers",
                        to="emr.location",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("is_home_collection", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("EN_ROUTE", "Phlebotomist en route"),
                            ("COLLECTED", "Collected"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_appointments",
                        to="emr.patient",
                    ),
                ),
                (
                    "phlebotomist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_appointments",
                        to="users.provider",
                    ),
                ),
                (
                    "collection_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="lis.collectioncenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.AddField(
            model_name="testorder",
            name="collection_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_orders",
                to="lis.collectioncenter",
            ),
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "gram_stain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="POSITIVE / NEGATIVE / N-A",
                        max_length=20,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicrobiologyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "growth",
                    models.CharField(
                        choices=[
                            ("NO_GROWTH", "No growth"),
                            ("GROWTH", "Growth"),
                            ("MIXED", "Mixed flora"),
                            ("CONTAMINATED", "Contaminated"),
                        ],
                        default="NO_GROWTH",
                        max_length=20,
                    ),
                ),
                (
                    "colony_count",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        default="PRELIMINARY",
                        help_text="PRELIMINARY / FINAL / AMENDED.",
                        max_length=20,
                    ),
                ),
                ("comments", models.CharField(blank=True, default="", max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="microbiology_results",
                        to="lis.specimen",
                    ),
                ),
                (
                    "test_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microbiology_results",
                        to="lis.testorder",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="isolates",
                        to="lis.organism",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="lis.client",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QCMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("lot_number", models.CharField(db_index=True, max_length=64)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Level 1 / Normal / High.",
                        max_length=20,
                    ),
                ),
                ("target_mean", models.FloatField()),
                ("target_sd", models.FloatField()),
                ("units", models.CharField(blank=True, default="", max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "analyte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_materials",
                        to="emr.concept",
                    ),
                ),
                (
                    "analyzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_materials",
                        to="lis.analyzer",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["analyte", "lot_number"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("default_tat_hours", models.PositiveIntegerField(default=72)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testorder",
            name="reference_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_orders",
                to="lis.referencelab",
            ),
        ),
        migrations.CreateModel(
            name="ReferringDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("specialty", models.CharField(blank=True, default="", max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("hospital", models.CharField(blank=True, default="", max_length=160)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testorder",
            name="referring_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_orders",
                to="lis.referringdoctor",
            ),
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("methodology_text", models.TextField(blank=True, default="")),
                ("interpretation_template", models.TextField(blank=True, default="")),
                ("footer_notes", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="lis.labtest",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "instrument",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="lis.labtest",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testorder",
            name="test_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_orders",
                to="lis.testmethod",
            ),
        ),
        migrations.CreateModel(
            name="TestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestProfileMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_weight", models.FloatField(default=0)),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_memberships",
                        to="lis.labtest",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="lis.testprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_weight"],
                "unique_together": {("profile", "lab_test")},
            },
        ),
        migrations.AddField(
            model_name="testprofile",
            name="tests",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                through="lis.TestProfileMember",
                to="lis.labtest",
            ),
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_items",
                        to="lis.labtest",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lis.pricelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("price_list", "lab_test")},
            },
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measured_value", models.FloatField()),
                ("z_score", models.FloatField(blank=True, null=True)),
                (
                    "westgard_rule",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Violated rule, e.g. 1-3s, 2-2s, R-4s; blank if in control.",
                        max_length=20,
                    ),
                ),
                ("accepted", models.BooleanField(default=True)),
                ("run_at", models.DateTimeField(db_index=True)),
                (
                    "analyzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_results",
                        to="lis.analyzer",
                    ),
                ),
                (
                    "qc_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lis.qcmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["-run_at"],
                "indexes": [
                    models.Index(
                        fields=["qc_material", "-run_at"],
                        name="lis_qcresul_qc_mate_48d997_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("portal", "Patient portal"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient"),
                            ("REFERRER", "Referring doctor"),
                            ("CLIENT", "B2B client"),
                        ],
                        default="PATIENT",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_deliveries",
                        to="notifications.notification",
                    ),
                ),
                (
                    "test_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_deliveries",
                        to="lis.testorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["test_order", "channel"],
                        name="lis_reportd_test_or_6aad80_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensitivityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        choices=[
                            ("S", "Sensitive"),
                            ("I", "Intermediate"),
                            ("R", "Resistant"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "mic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Minimum inhibitory concentration, if measured.",
                        max_length=32,
                    ),
                ),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitivities",
                        to="lis.antibiotic",
                    ),
                ),
                (
                    "microbiology_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivities",
                        to="lis.microbiologyresult",
                    ),
                ),
            ],
            options={
                "ordering": ["antibiotic__name"],
                "unique_together": {("microbiology_result", "antibiotic")},
            },
        ),
        migrations.CreateModel(
            name="ReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("A", "Any"), ("M", "Male"), ("F", "Female")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("age_min_days", models.IntegerField(blank=True, null=True)),
                ("age_max_days", models.IntegerField(blank=True, null=True)),
                ("low_normal", models.FloatField(blank=True, null=True)),
                ("hi_normal", models.FloatField(blank=True, null=True)),
                ("low_critical", models.FloatField(blank=True, null=True)),
                ("hi_critical", models.FloatField(blank=True, null=True)),
                ("units", models.CharField(blank=True, default="", max_length=50)),
                (
                    "text_range",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display string, e.g. '12 - 16 g/dL' or 'Negative'.",
                        max_length=120,
                    ),
                ),
                (
                    "analyte",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific analyte for panels; null applies to the test itself.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_ranges",
                        to="emr.concept",
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="lis.labtest",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reference_ranges",
                        to="lis.testmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["lab_test", "sex", "age_min_days"],
                "indexes": [
                    models.Index(
                        fields=["lab_test", "analyte", "sex"],
                        name="lis_referen_lab_tes_9c1fa5_idx",
                    )
                ],
            },
        ),
    ]
