# Generated by Django 5.1.15 on 2026-06-21 10:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_initial"),
        ("pos", "0006_payment_account_quotation_quotationline_salesreturn_and_more"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("flutterwave", "Flutterwave"),
                            ("lenco", "Lenco"),
                            ("manual", "Manual / test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_test", models.BooleanField(default=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "supported_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of channels, e.g. ['CARD', 'MOBILE_MONEY'].",
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateways",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("CARD", "Card"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("BANK", "Bank transfer"),
                            ("USSD", "USSD"),
                        ],
                        default="CARD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intents",
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intents",
                        to="pos.sale",
                    ),
                ),
                (
                    "settled_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_intent",
                        to="pos.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("flutterwave", "Flutterwave"),
                            ("lenco", "Lenco"),
                            ("manual", "Manual / test"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=80)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="payments.paymentgateway",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_6cb6dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "provider_event_id"],
                name="payments_we_provide_2c5c19_idx",
            ),
        ),
    ]
