# Generated by Django 5.1.15 on 2026-06-20 23:59

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sku", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("is_drug", models.BooleanField(default=False)),
                (
                    "is_controlled",
                    models.BooleanField(
                        default=False, help_text="Controlled/scheduled drug."
                    ),
                ),
                ("strength", models.CharField(blank=True, default="", max_length=64)),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("track_batches", models.BooleanField(default=True)),
                ("track_expiry", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "po_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("PARTIAL", "Partially received"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name_plural": "stock batches",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Goods receipt"),
                            ("SALE", "Sale / POS"),
                            ("DISPENSE", "Pharmacy dispense"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("RETURN", "Return"),
                            ("WASTAGE", "Wastage / expiry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "tax_identifier",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HSN/SAC code for GST compliance.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique, FHIR-friendly identifier.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retired", models.BooleanField(db_index=True, default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retire_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="", max_length=20),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
