# Generated by Django 5.1.15 on 2026-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stockbatch",
            options={
                "ordering": ["expiry_date", "id"],
                "verbose_name_plural": "stock batches",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={"ordering": ["name"]},
        ),
    ]
