# Generated by Django 5.1.15 on 2026-06-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_alter_product_options_alter_purchaseorder_options_and_more",
        ),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="tenancy.organization",
            ),
        ),
    ]
