# Generated by Django 5.1.15 on 2026-06-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0005_cohort_conceptattributetype_conceptattribute_and_more"),
        ("inventory", "0004_product_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="drug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="emr.drug",
            ),
        ),
    ]
