# Generated by Django 5.1.15 on 2026-06-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPENSED", "Dispensed"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DISPENSED",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="emr.order",
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dose_units", models.CharField(blank=True, default="", max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. BD, TDS, QID, OD",
                        max_length=50,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PO, IV, IM, ...",
                        max_length=50,
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_units",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("num_refills", models.PositiveSmallIntegerField(default=0)),
                ("as_needed", models.BooleanField(default=False)),
                ("dosing_instructions", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "drug order",
            },
            bases=("emr.order",),
        ),
    ]
