# Generated by Django 5.1.15 on 2026-06-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0002_initial"),
        ("inventory", "0002_initial"),
        ("pharmacy", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispense",
            name="dispensed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispenses",
                to="users.provider",
            ),
        ),
        migrations.AddField(
            model_name="dispense",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispenses",
                to="emr.location",
            ),
        ),
        migrations.AddField(
            model_name="dispense",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispenses",
                to="emr.patient",
            ),
        ),
        migrations.AddField(
            model_name="dispense",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispenses",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="drugorder",
            name="drug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drug_orders",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="dispense",
            name="drug_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispenses",
                to="pharmacy.drugorder",
            ),
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(
                fields=["patient", "-created_at"], name="pharmacy_di_patient_7073e4_idx"
            ),
        ),
    ]
