# Generated by Django 5.1.15 on 2026-06-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0005_cohort_conceptattributetype_conceptattribute_and_more"),
        ("pharmacy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugorder",
            name="drug_formulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drug_orders",
                to="emr.drug",
            ),
        ),
        migrations.AddField(
            model_name="drugorder",
            name="order_frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drug_orders",
                to="emr.orderfrequency",
            ),
        ),
    ]
