# Generated by Django 5.1.15 on 2026-06-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_purchasebill_purchasebillitem_and_more"),
        ("pharmacy", "0003_drugorder_drug_formulation_drugorder_order_frequency"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispenseBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "dispense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_lines",
                        to="pharmacy.dispense",
                    ),
                ),
            ],
        ),
    ]
