# Generated by Django 5.1.15 on 2026-06-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0004_dispensebatch"),
        ("pos", "0007_saleline_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispense",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispenses",
                to="pos.sale",
            ),
        ),
    ]
