# Generated by Django 5.1.15 on 2026-06-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_billableservice_options_and_more"),
        ("lis", "0006_testorder_is_outsourced_antibiotic_and_more"),
        ("pos", "0004_sale_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="lis.client",
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="billable_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_lines",
                to="billing.billableservice",
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="test_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_lines",
                to="lis.testprofile",
            ),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("SERVICE", "Service"),
                    ("LAB_TEST", "Lab test"),
                    ("LAB_PROFILE", "Lab profile"),
                    ("CONSULTATION", "Consultation"),
                ],
                default="PRODUCT",
                max_length=20,
            ),
        ),
    ]
