# Generated by Django 5.1.15 on 2026-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_payment_account_quotation_quotationline_salesreturn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="fulfilled",
            field=models.BooleanField(
                default=False,
                help_text="True once a non-stock line has been fulfilled (e.g. a lab test order created for a LAB_TEST/LAB_PROFILE line).",
            ),
        ),
    ]
